// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzjwMKr3wh_SelLZT5H6lSKGBmYFZYmw',
    appId: '1:107339187331:web:b2d51aa31fba0867d747b6',
    messagingSenderId: '107339187331',
    projectId: 'fising-cd57c',
    authDomain: 'fising-cd57c.firebaseapp.com',
    storageBucket: 'fising-cd57c.appspot.com',
    measurementId: 'G-ZQH4SLT680',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIuwaLy5HvTgOId8yeOFgO5XjgdjzKJX4',
    appId: '1:107339187331:android:f69d82d086bcad98d747b6',
    messagingSenderId: '107339187331',
    projectId: 'fising-cd57c',
    storageBucket: 'fising-cd57c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-y-0QeiiNXdlUmmHMMPQfVXr4k_0zvc',
    appId: '1:107339187331:ios:9ba3e42ece47eb9ed747b6',
    messagingSenderId: '107339187331',
    projectId: 'fising-cd57c',
    storageBucket: 'fising-cd57c.appspot.com',
    iosBundleId: 'com.example.takayamaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-y-0QeiiNXdlUmmHMMPQfVXr4k_0zvc',
    appId: '1:107339187331:ios:901e6873cdf6ada0d747b6',
    messagingSenderId: '107339187331',
    projectId: 'fising-cd57c',
    storageBucket: 'fising-cd57c.appspot.com',
    iosBundleId: 'com.example.takayamaTest.RunnerTests',
  );
}
